
# display dishes
GET http://localhost:3007/api/dishes


### display dishes for item
GET http://localhost:3007/api/dishes/oat


### select dish
GET http://localhost:3007/api/dishes/1

### display results for selected dish
GET http://localhost:3007/api/recipes/1




